# Generated by Django 2.1 on 2020-12-27 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20201227_0332'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
