# Generated by Django 2.1 on 2021-01-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210129_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=45)),
                ('date', models.CharField(max_length=20)),
                ('search_word', models.CharField(max_length=50)),
                ('search_date_interval', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=2083)),
            ],
        ),
    ]
