# Generated by Django 2.1 on 2021-01-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_posttitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttitle',
            name='sentiment',
            field=models.CharField(default='No Info', max_length=10),
        ),
        migrations.AddField(
            model_name='posttitle',
            name='sentiment_degree',
            field=models.FloatField(default=0.0),
        ),
    ]
