version: "3.7"

x-service-volumes: &service-volumes
  - ./:/app/:rw,cached

services:
  website:
    image: swe-573-website:latest
    command: python manage.py runserver 0.0.0.0:8000
    volumes: *service-volumes
    depends_on:
      - db-migrate
    ports: 
      - "8000:8000"

  db-migrate:
    image: swe-573-website:latest
    command: python manage.py migrate
    volumes: *service-volumes