# Generated by Django 2.1 on 2021-01-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=20)),
                ('search_word', models.CharField(max_length=50)),
                ('search_date_interval', models.CharField(max_length=20)),
            ],
        ),
    ]
