# Generated by Django 2.1 on 2021-01-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210130_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posttitle',
            old_name='sentiment_degree',
            new_name='sentiment_polarity',
        ),
        migrations.AddField(
            model_name='posttitle',
            name='sentiment_subj',
            field=models.FloatField(default=0.0),
        ),
    ]
