# Generated by Django 2.1 on 2020-12-27 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_customusermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newusermodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='NewUserModel',
        ),
    ]
